# Generated by Django 3.0.5 on 2020-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure_type',
            field=models.CharField(max_length=5),
            preserve_default=False,
        ),
    ]
