# Generated by Django 2.1.15 on 2020-05-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200503_2319'),
        ('services', '0002_auto_20200503_2317'),
    ]

    operations = [
    ]
